version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - devexpress
registries:
  devexpress:
    type: nuget-feed
    url: https://nuget-test.devexpress.com/api
    token: ${{secrets.DXTOKEN}}
